version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR


  build:
    commands:
      - echo Build started
      - echo Building the docker image



  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...

     - echo Writing image definition file..



artifacts:
  files:
    - imagedefinitions.json
